name: Publish Nuget Package

on: 
  workflow_call:
    
jobs:
  PublishNugetPackage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - id: get-version
        run: source .env && echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish Sync Nuget and Tag Commit
        run: |
          dotnet build ManualDi.Sync --configuration Release
          dotnet pack ManualDi.Sync --configuration Release --output ManualDi.Sync.Nuget -p:PackageVersion=$versionç
          
          set +e  # Disable immediate exit on error
          dotnet nuget push "ManualDi.Sync.Nuget/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{secrets.NUGET_API_KEY}}"
          push_result=$?
          set -e  # Enable immediate exit on error

          if [ $push_result -ne 0 ]; then
            echo "Package could not be pushed, assuming a package with that version is already present"
            exit 0
          fi

          echo "NuGet package pushed successfully"

      - name: Publish Async Nuget and Tag Commit
        run: |
          dotnet build ManualDi.Async --configuration Release
          dotnet pack ManualDi.Async --configuration Release --output ManualDi.Async.Nuget -p:PackageVersion=$version
          
          set +e  # Disable immediate exit on error
          dotnet nuget push "ManualDi.Async.Nuget/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{secrets.NUGET_API_KEY}}"
          push_result=$?
          set -e  # Enable immediate exit on error

          if [ $push_result -ne 0 ]; then
            echo "Package could not be pushed, assuming a package with that version is already present"
            exit 0
          fi

          echo "NuGet package pushed successfully"


          