name: Publish Unity3d Sync Package
on: 
  workflow_call:

jobs:
  PublishUnity3dPackage:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - id: get-version
        run: |
          source .env
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: release-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_exists=$(gh release view "v${{ steps.get-version.outputs.version }}" &> /dev/null && echo "true" || echo "false")
          echo "Release exists $release_exists"
          echo "exists=$release_exists" >> $GITHUB_OUTPUT

      - name: Create Sync Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          bash ./ManualDi.Sync.Unity3d/GenerateUnityPackage/GeneratePackage.sh

      - name: Create Async Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          bash ./ManualDi.Async.Unity3d/GenerateUnityPackage/GeneratePackage.sh

      - name: Create github release
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: ManualDi Unity3d v${{ steps.get-version.outputs.version }}
          files: |
            ManualDi.Sync.Unity3d.Package/com.pereviader.manualdi.sync.unity3d-${{ steps.get-version.outputs.version }}.tgz
            ManualDi.Async.Unity3d.Package/com.pereviader.manualdi.async.unity3d-${{ steps.get-version.outputs.version }}.tgz

      - name: Trigger Unity3d Repo Workflow
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_UNITY3D }}
        run: |
          gh workflow run PublishUnity3dPackage.yml \
            --repo PereViader/ManualDi.Unity3d \
            --ref main \
            -f release-tag=v${{ steps.get-version.outputs.version }} \
            -f sync-file-name=com.pereviader.manualdi.sync.unity3d-${{ steps.get-version.outputs.version }}.tgz
            -f async-file-name=com.pereviader.manualdi.async.unity3d-${{ steps.get-version.outputs.version }}.tgz