name: Publish Unity3d Package
on: 
  workflow_call:

env:
  version_file: ManualDi.Main/ManualDi.Main.csproj

jobs:
  PublishUnity3dPackage:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - id: get-version
        run: |
          version=$(grep -oP '(?<=<Version>)[^<]+' "${{ env.version_file }}")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: release-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_exists=$(gh release view "Unity3d/${{ steps.get-version.outputs.version }}" &> /dev/null && echo "true" || echo "false")
          echo "Release exists $release_exists"
          echo "exists=$release_exists" >> $GITHUB_OUTPUT

      - name: Create Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          sh ./GenerateUnityPackage/GeneratePackage.sh

      - name: Create github release
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Unity3d/${{ steps.get-version.outputs.version }}
          name: Unity3d ManualDi.Main ${{ steps.get-version.outputs.version }}
          files: |
            UnityPackageRelease/me.pereviader.manualdi.main-${{ steps.get-version.outputs.version }}.tgz

      - name: Trigger Unity3d Repo Workflow
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run PublishUnity3dPackage.yml \
            --repo PereViader/ManualDi.Unity3d \
            --ref main \
            -f release-tag=Unity3d/${{ steps.get-version.outputs.version }}
            -f file-name=me.pereviader.manualdi.main-${{ steps.get-version.outputs.version }}.tgz