name: Publish Unity3d Sync Package
on: 
  workflow_call:

jobs:
  PublishUnity3dPackage:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0

      - id: get-version
        run: |
          source .env.shared
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" == *preview* ]]; then
            echo "isPrerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "isPrerelease=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if release exists
        id: release-exists
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          release_exists=$(gh release view "v${{ steps.get-version.outputs.version }}" &> /dev/null && echo "true" || echo "false")
          echo "Release exists $release_exists"
          echo "exists=$release_exists" >> $GITHUB_OUTPUT

      - name: Get changelog
        id: get-changelog
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          payload=$(git log $(git describe --tags --abbrev=0 main)..main --pretty=format:"%s%n%b")
          echo "changelog<<EOF"$'\n'"$payload"$'\n'EOF >> "$GITHUB_OUTPUT"

      - name: Create Sync Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          bash ./ManualDi.Sync.Unity3d/GenerateUnityPackage/GeneratePackage.sh

      - name: Create Async Package
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        run: |
          bash ./ManualDi.Async.Unity3d/GenerateUnityPackage/GeneratePackage.sh

      - name: Create github release
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: ManualDi Unity3d v${{ steps.get-version.outputs.version }}
          body: ${{ steps.get-changelog.outputs.changelog }}
          prerelease: ${{ steps.get-version.outputs.isPrerelease }}
          files: |
            ManualDi.Sync.Unity3d.Package/com.pereviader.manualdi.sync.unity3d-${{ steps.get-version.outputs.version }}.tgz
            ManualDi.Async.Unity3d.Package/com.pereviader.manualdi.async.unity3d-${{ steps.get-version.outputs.version }}.tgz

      - name: Trigger Sync OpenUPM Publish
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.OPENUPM_GITHUB_TOKEN }}
        run: |
          gh workflow run Publish.yml \
            --repo PereViader/OpenUPM \
            --ref main \
            -f ingest_url=https://github.com/PereViader/ManualDi/releases/download/v${{ steps.get-version.outputs.version }}/com.pereviader.manualdi.sync.unity3d-${{ steps.get-version.outputs.version }}.tgz

      - name: Trigger Async OpenUPM Publish
        if: ${{ steps.release-exists.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.OPENUPM_GITHUB_TOKEN }}
        run: |
          gh workflow run Publish.yml \
            --repo PereViader/OpenUPM \
            --ref main \
            -f ingest_url=https://github.com/PereViader/ManualDi/releases/download/v${{ steps.get-version.outputs.version }}/com.pereviader.manualdi.async.unity3d-${{ steps.get-version.outputs.version }}.tgz