name: Publish Nuget Package

on: 
  workflow_call:

env:
  version_file: ManualDi.Main/ManualDi.Main/ManualDi.Main.csproj
    
jobs:
  PublishNugetPackage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - id: get-version
        run: |
          version=$(grep -oP '(?<=<Version>)[^<]+' "${{ env.version_file }}")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Publish Nuget and Tag Commit
        run: |
          dotnet build ManualDi.Main --configuration Release
          dotnet pack ManualDi.Main --configuration Release --output NugetPackageRelease
          set +e  # Disable immediate exit on error
          dotnet nuget push "NugetPackageRelease/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{secrets.NUGET_API_KEY}}"
          push_result=$?
          set -e  # Enable immediate exit on error

          if [ $push_result -ne 0 ]; then
            echo "Package could not be pushed, assuming a package with that version is already present"
            exit 0
          fi

          echo "NuGet package pushed successfully"