name: Test

on: 
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - run: dotnet test ManualDi.Sync

      - run: dotnet test ManualDi.Async